CREATE DATABASE AndORNotExample;
USE AndORNotExample;
CREATE TABLE Customers(
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(255),
CUSTOMER_ADRESS VARCHAR(255),
CUSTOMER_CITY VARCHAR(255),
CUSTOMER_COUNTRY VARCHAR(255)
);

INSERT INTO Customers VALUES (1, "SUSMITA MALI", "MANGLWAR PETH 416012", "KOLHAPUR", "INDIA"),
(2, "SHUBHAM PATIL", "THANE EAST", "MUMBAI", "INDIA"),
(3, "POOJA KULKARNI", "SADASHIV PETH", "PUNE", "INDIA"),
(4, "ELIXA", "BUNGLOW 234", "LONDON", "UK"),
(5, "SHINCHAN", "HOUSE NO 34", "BEIJING", "CHINA"),
(6, "SAYAMA", "JANNAT BUNGLOW", "KARACHI", "PAKISTAN"),
(7, "JULI", "HOUSE 120 HANOVER Sq.", "ROME", "ITALY"),
(8, "PAT CUMMINS", "PAT VILLA 2", "CANERRA", "AUSTRALIA" ),
(9, "RASHID KHAN ", "HOUSE No. 45", "KUWAIT CITY", "KUWAIT"),
(10, "THOMAS HARDY", "24 PAINT HOUSE", "PARIS","FRANCE");

SELECT * FROM Customers ;

-- WHERE 

SELECT * FROM Customers 
WHERE CUSTOMER_COUNTRY = "INDIA" ;

-- AND 
SELECT * FROM Customers 
WHERE CUSTOMER_COUNTRY = "INDIA" AND CUSTOMER_CITY = "PUNE";

-- OR
SELECT * FROM Customers
WHERE CUSTOMER_CITY = "MUMBAI" OR CUSTOMER_CITY = "KOLHAPUR";

-- NOT
SELECT * FROM Customers 
WHERE NOT CUSTOMER_COUNTRY = "PAKISTAN";

-- COMBINING AND ,OR ,NOT
SELECT * FROM Customers 
WHERE CUSTOMER_COUNTRY= "INDIA" AND (CUSTOMER_CITY = "PUNE" OR CUSTOMER_CITY = "KOHAPUR" ); 

-- ORDER BY 
SELECT * FROM Customers 
ORDER BY CUSTOMER_COUNTRY; 

-- ORDER BY desc
SELECT * FROM Customers
ORDER BY CUSTOMER_COUNTRY DESC; 
 
-- ORDER BY SEVERAL COLOUMS EXAMPLE (The following SQL statement selects all customers from the "Customers" table, sorted by the "Country" and the "CustomerName" column. This means that it orders by Country, but if some rows have the same Country, it orders them by CustomerName:)
SELECT * FROM Customers
ORDER BY CUSTOMER_COUNTRY, CUSTOMER_NAME; 

SELECT * FROM Customers 
ORDER BY CUSTOMER_COUNTRY ASC, CUSTOMER_NAME DESC; 



