CREATE DATABASE BanksInfo;
USE BanksInfo;
CREATE TABLE Office(
BANK_NAME VARCHAR(255),
BANK_BRANCH VARCHAR(255),
BANK_IFSCCODE INT,
BANK_LOANPERCENTAGE INT,
BANK_BRANCHCODE INT
);

INSERT INTO Office (BANK_NAME, BANK_BRANCH, BANK_IFSCCODE, BANK_LOANPERCENTAGE, BANK_BRANCHCODE)
VALUES
("SBI", "SATARA", 25478963, 7.5, 1);

INSERT INTO Office (BANK_NAME, BANK_BRANCH, BANK_IFSCCODE, BANK_LOANPERCENTAGE, BANK_BRANCHCODE)
VALUES
("HDFC", "PUNE", 266578, 7.9, 2);

INSERT INTO Office (BANK_NAME, BANK_BRANCH, BANK_IFSCCODE, BANK_LOANPERCENTAGE, BANK_BRANCHCODE)
VALUES
("BOI", "KOLHAPUR", 14646843, 8, 1);

INSERT INTO Office (BANK_NAME, BANK_BRANCH, BANK_IFSCCODE, BANK_LOANPERCENTAGE, BANK_BRANCHCODE)
VALUES
("IDBI", "SANGLI", 154564, 7.6, 2);

INSERT INTO Office (BANK_NAME, BANK_BRANCH, BANK_IFSCCODE, BANK_LOANPERCENTAGE, BANK_BRANCHCODE)
VALUES
("BOM", "KARAD", 254887, 8, 1 );

SELECT * FROM Office;
