CREATE DATABASE Company;
USE COMPANY;
CREATE TABLE Information (
ID INT,
EMPLOYEE_NAME varchar(255),
EMPLOYEE_SALARY INT,
EMPLOYEE_POST VARCHAR(255),
EMPLOYEE_DEPARTMENT VARCHAR(255)
);

INSERT INTO Information ( ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_POST, EMPLOYEE_DEPARTMENT)
VALUES 
(1, "SUSMITA", 25000, "ENGINEER", "SOFTWARE");

INSERT INTO Information (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_POST, EMPLOYEE_DEPARTMENT)
VALUES
(2, "KOMAL", 30000, "ENGINEER", "DEVELOPER");

INSERT INTO Information (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_POST, EMPLOYEE_DEPARTMENT)
VALUES
(3, "SAMIKSHA", 35000, "DESIGNER", "AUTOCAD");

INSERT INTO Information (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_POST, EMPLOYEE_DEPARTMENT)
VALUES
(4, "NAMRATA", 40000, "ENGINEER", "AUTOMATION");

INSERT INTO Information (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_POST, EMPLOYEE_DEPARTMENT)
VALUES
(5, "KAJAL", 50000, "ENGINEER", "MANAGER");