CREATE DATABASE HOMEAPPLIANCES;
USE HOMEAPPLIANCES;
CREATE TABLE HOME(
KITCHEN_TOOLS VARCHAR(255),
KITCHEN_TOOLFUNCTION VARCHAR(255),
KITCHEN_TOOLNO INT,
KITCHEN_TOOLBRAND VARCHAR(255),
KITCHEN_TOOLMATERIAL VARCHAR(255)
);

INSERT INTO HOME VALUES ("COOKER", "COOK", 1, "PRESTIGE", "STEEL"),
("MIXER", "CHOP", 2, "PIGEON", "STEEL"),
("MICROWAVE", "COOK", 3, "PRESTIGE", "GLASS"),
("PURIFIRE","FILTER", 4, "PIGEON", "FIBER"),
("WATERBOTTLE", "STORE", 5, "MILTON", "STEEL");

SELECT * FROM HOME;

-- WHERE
SELECT * FROM HOME 
WHERE 
KITCHEN_TOOLS = "COOKER";

-- AND 
SELECT * FROM HOME 
WHERE KITCHEN_TOOLS = "MIXER" AND KITCHEN_TOOLNO = 2;

-- OR
SELECT * FROM HOME
WHERE KITCHEN_TOOLS = "MIXER" OR KITCHEN_TOOLS = "PURIFIER";

-- NOT 
SELECT * FROM HOME 
WHERE NOT KITCHEN_TOOLS = "WATERBOTTLE";

-- COMBINING AND OR & NOT 
SELECT * FROM HOME 
WHERE KITCHEN_TOOLBRAND = "PIGEON" AND (KITCHEN_TOOLS= "MIXER" OR KITCHEN_TOOLS = "PURIFIRE");

-- ORDER BY
SELECT * FROM HOME 
ORDER BY KITCHEN_TOOLS;

-- ORDER BY DESC 
SELECT * FROM HOME 
ORDER BY KITCHEN_TOOLNO DESC;

-- ORDER BY SEVERAL COLOUMN EXAMPLE 
SELECT * FROM HOME 
ORDER BY KITCHEN_TOOLMATERIAL , KITCHEN_TOOLFUNCTION; 

-- ORDER BY SEVERAL COLOUMN ASC DESC
SELECT * FROM HOME customersinformationcustomers
ORDER BY KITCHEN_TOOLS ASC, KITCHEN_TOOLNO DESC; 

