CREATE DATABASE FOODDELIVERY;
USE FOODDELIVERY;
CREATE TABLE RESTAURANT (
DISH_NAME VARCHAR(255),
DISH_PRICE INT, 
DISH_TYPE VARCHAR(255),
DISH_DELIVERYTIME VARCHAR(255),
DISH_PACKAGINGCHARGE int
);

INSERT INTO RESTAURANT VALUES ("IDALI", 50, "VEG", "10 MINS", 10),
 ("MISAL", 60, "VEG", "20 MINS", 20),
 ("BIRYANI", 150, "NONVEG", "20 MINS", 20),
 ("THALIPITH", 70, "VEG", "30 MINS", 15),
 ("PIZZA", 100, "NONVEG", "45 MINS", 25);
    
SELECT * FROM RESTAURANT ;

-- WHERE
SELECT *  FROM RESTAURANT 
WHERE DISH_NAME = "MISAL";

-- AND 
SELECT * FROM RESTAURANT 
WHERE DISH_NAME = "IDALI" AND DISH_PRICE = 50; 

-- OR
SELECT * FROM RESTAURANT 
WHERE DISH_NAME ="BIRYANI" OR DISH_NAME= "PIZZA" ;

-- WHERE NOT 
SELECT * FROM RESTAURANT 
WHERE NOT DISH_PRICE = 50;

-- ORDER BY 
SELECT * FROM RESTAURANT 
ORDER BY DISH_NAME ;

-- ORDER BY DESC 
SELECT * FROM RESTAURANT 
ORDER BY DISH_PRICE DESC; 

SELECT * FROM RESTAURANT 
ORDER BY DISH_PRICE ASC,  DISH_TYPE DESC ;

