CREATE DATABASE School;
USE School;
CREATE TABLE Class(
ID int,
STUDENT_NAME VARCHAR(255),
STUDENT_CLASS INT,
STUDENT_DIV VARCHAR(255),
STUDENT_PERCENTAGE INT
);

INSERT INTO Class (ID, STUDENT_NAME, STUDENT_CLASS, STUDENT_DIV, STUDENT_PERCENTAGE)
VALUES
(1, "SHUBHAM", 5, "A", 78);

INSERT INTO Class (ID, STUDENT_NAME, STUDENT_CLASS, STUDENT_DIV, STUDENT_PERCENTAGE)
VALUES
(2, "SAMARTH", 5, "A", 86);

INSERT INTO Class (ID, STUDENT_NAME, STUDENT_CLASS, STUDENT_DIV, STUDENT_PERCENTAGE)
VALUES
(3, "PAVAN", 5, "B", 84);

INSERT INTO Class (ID, STUDENT_NAME, STUDENT_CLASS, STUDENT_DIV, STUDENT_PERCENTAGE)
VALUES
(4, "NAMRATA", 5, "B", 92);

INSERT INTO Class (ID, STUDENT_NAME, STUDENT_CLASS, STUDENT_DIV, STUDENT_PERCENTAGE)
VALUES
(5, "SUSMITA", 5, "C", 89);

SELECT * FROM Class; 

SELECT * FROM Class
WHERE 
STUDENT_NAME = "SHUBHAM";



